
server:
  port: 8092
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zp365072035/exercise-cloud
          default-label: master
          search-paths: config
          username: 365072035@qq.com
          password: 1p1l1m8mmg
